#!/bin/python3

import sys


# Q 9.7 Inorder traversal without recursion, figure pg 116
LOOKUPS= 0

def main(argv):
	
	print ("Creating bin tree")

	tree = createBinaryTreeManually()
	
	print("Doing : inorder_tree_traversal")
	inorder_tree_traversal(tree)
	print('\n')
	print("Doing : No RECURSION inorder_tree_traversal")
	print("by basically simulating function call stack")
        #1. Logic is push node to stack and go left  
        #2. if node is null
                # - then pop stack, this is the result
                # move to right node
	#inorder_tree_traversal_with_stack(tree)
	inorder_tree_traversal_with_stack_practise(tree)
	print('\n')

def inorder_tree_traversal_with_stack_practise(node):
	
	result = []
	stack = []

        
	while node or stack:
        
		if node:
			stack.append(node)
			node = node.left
		else:
			n = stack.pop()
			print("At {}".format(n.data))
			node = n.right	
			       
def inorder_tree_traversal_with_stack(node):
	
        result = []
        stack = []

        #TODO Sanity checks

        while node or stack:
        
                if(node):
                        stack.append(node)
                        node = node.left
                else:
                        x = stack.pop()
                        print("At {}".format(x.data))
                        node = x.right
	
def inorder_tree_traversal(root):
	
	if root:
		inorder_tree_traversal(root.left)
		##sys.stdout.write("{},".format(root.data))
		print(" At {}".format(root.data))
		inorder_tree_traversal(root.right)

def preorder_tree_traversal(root):
	
	if root:		
		##sys.stdout.write("{},".format(root.data))
		print(" At {}".format(root.data))
		preorder_tree_traversal(root.left)
		preorder_tree_traversal(root.right)

# Tree on Fig 9.2, pg 11
def createBinaryTreeManually():
        
        #leaf_1 = Btn('E')
        #leaf_2 = Btn('F')
        leaf_1 = Btn('E', Btn('X'), None)
        leaf_2 = Btn('F', None, Btn('Y'))        
        leaf_3 = Btn('I')
        leaf_4 = Btn('J')
        leaf_5 = Btn('M')
        leaf_6 = Btn('N')
	
        d3_1 = Btn('D', leaf_1, leaf_2)
        d3_2 = Btn('G')

        d2_1 = Btn('C', d3_1, d3_2)
        d2_2 = Btn('H', leaf_3, leaf_4)
        d2_3 = Btn('L', leaf_5,leaf_6)
        d2_4 = Btn('O')

        d1_1 = Btn('B',d2_1, d2_2)
        d1_2 = Btn('K',d2_3, d2_4)

        d0 = Btn('A', d1_1, d1_2)
        return d0

# Tree on Fig 9.1, pg 113
def createBinaryTreeManually2():
	
	leaf_1 = Btn(641)
	leaf_2 = Btn(257)
	leaf_3 = Btn(17)
	leaf_4 = Btn(28)
	leaf_5 = Btn(28)
	leaf_6 = Btn(0)

	d4_1 = Btn(401,None,leaf_1)
	
	d3_1 = Btn(3, leaf_3, None)
	d3_2 = Btn(1, d4_1, leaf_2)

	d2_1 = Btn(271, leaf_4,leaf_6)
	d2_2 = Btn(561, None, d3_1)
	d2_3 = Btn(2, None,d3_2)
	d2_4 = Btn(271,None,leaf_5)

	d1_1 = Btn(6,d2_1, d2_2)
	d1_2 = Btn(6,d2_3, d2_4)

	d0 = Btn(314, d1_1, d1_2)
	return d0

#Binary tree node
class Btn():

	def __init__(self, node_data, left_node=None, right_node=None):

		self.data = node_data
		self.left = left_node
		self.right = right_node
	
	def __str__(self):

		return str(self.data)

if __name__ == "__main__":main(sys.argv[0:])
