#!/bin/python3

import sys
# Question 5.2 , add one to integer representation
def main(argv):

	testcase_1 = [1,2,0,9] #should become 1210
	testcase_2 = [2, 1, 0] #should become 211
	testcase_3 = [9,9,8] #should become 1000 
	testcase = testcase_3

	#Prints only last number
	print(testcase[-1])
	
	#Prints everything except last number
	print(testcase[:-1])

	addOne(testcase)

	print("Result: " + str(testcase))

def addOne(a):
	
	print ("Running addOne problem..")

	a[-1]+=1 #Add one to last digit, like grade-school addition
	
	# It needs to iterate reversed because array insertion at beginning is O(N) and
	# at end is O(1)

	for i in reversed(range(1,len(a))):
		#print("I:{}, arr:{}".format(i,str(a[i])))
		if a[i] == 10:
			a[i], a[i-1] = 0, a[i-1]+1 
			#print(str(a))
		
	if(a[0]==10):
		a[0] = 0
		a.insert(0,1) #Add extra digit(shifts entire array)
 
if __name__ == "__main__":main(sys.argv[0:])
