#!/bin/python3

import sys

def main(argv):
	# Assume unsorted
	testcase_1 = [1,2,0,0,0,0,3,5]


	# Assume sorted(then we can swap element by element)
	testcase_2 = [1,1,3,6,7,8,9,9,9]
	testcase_3 = [1,1, 2,2,2,5,5,6]
	testcase_4 = [2,4,6,8,9,10]
	testcase = testcase_3
	result = removeDupli(testcase)

	print("Result: " + str(result))

#Using a set
def remDupli(arr):

	s = { i for i in arr }
	
	return list(s)

def removeDupli(arr):
	
	arr.sort()
	end = len(arr)-1
	
	i=1
	
	while i<end:
		if arr[i-1]==arr[i]:
			shift_left(arr, i, end)
			end-=1
		else:	
			i+=1	
	
	return arr
	
def shift_left(arr, index, end):

	print(arr, index, end)
	
	for i in range(index, end):
		#print("Index:", i, arr[index])		
		arr[i] = arr[i+1]
	
	arr[end] = 0	
			
if __name__ == "__main__":main(sys.argv[0:])
