#!/bin/python3

import bisect
import sys

# 13.1 EPIP compute intersection of sorted arrays

# When 2 list are almost same size
def intersection(left, right):

	result = set()
	
	p1=p2=0

	while p1<len(left) and p2<len(right):
	
		if left[p1] == right[p2]:
			result.add(left[p1])
			p1, p2 = p1+1, p2+1
		elif left[p1]<right[p2]:
			p1+=1
		else:
			p2+=1
	
	return result
			
def main(argv):

	l = [1, 2, 3, 4, 4, 4, 6, 7]
	r = [2,4,4,4,5,6,6,6,6,6,7]
	
	result = intersection(l, r)
	
	print(result)
      

if __name__ == "__main__":main(sys.argv[0:])
